
apiVersion: v1
kind: Pod
metadata:
  name: nvidia-test-pod
spec:

    runtimeClassName: nvidia
    restartPolicy: Never
    nodeName: eddie-gpu #$REPLACE_WITH_THE_NAME_OF_YOUR_GPU_NODE
    containers:
      - name: nvidia-test
        image: nvidia/cuda:12.0.0-base-ubuntu22.04
        command: [ "nvidia-smi" ]
        env:
          - name: TORCH_CUDA_ARCH_LIST
            value: "8.6"
          - name: NVIDIA_VISIBLE_DEVICES
            value: "all"
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: "all"

